image_size: 2048
exp_name: efficientnetb5
val_fold: 2
seed: 2025
matmul_precision: medium

model:
  encoder_name: efficientnet-b5
  encoder_weights: imagenet
  in_chans: 3
  lr: 0.0003
  dropout_rate: 0.35

trainer:
  devices: 1
  strategy: auto
  precision: 16-mixed
  max_epochs: 120
  accumulate_grad_batches: 1
  num_sanity_val_steps: 0
  deterministic: true
  benchmark: false

data_loader:
  train:
    batch_size: 2
    num_workers: 12
    prefetch_factor: 2
    shuffle: true
    drop_last: false
    pin_memory: true
    persistent_workers: true
    pin_memory_device: cuda
  val:
    batch_size: 2
    num_workers: 12
    prefetch_factor: 2
    shuffle: false
    drop_last: false
    pin_memory: true
    persistent_workers: true
